### ISSUE TITLE
Does not appear aligned in Mobile Safari

### ISSUE THREAD

**Issue by jeremy-w** [chris-martin/haskell-aligned#2]
The grouping comes through, but the alignment does not. "Maybe try a table" whispers the 1990s. Soon the voice will recommend spacer gifs too, so forget that, amirite?

![image](https://cloud.githubusercontent.com/assets/29010/16546475/90124436-4119-11e6-866b-0ce42b69d967.png)

**Comment by chris-martin** [comment]
I think the easiest workaround will be to replace spaces with `&nbsp;`, as we did in the 90s.

I'm not an Apple customer; do they have a bugtracker where you can report this issue?

**Comment by jeremy-w** [comment]
bugreport.apple.com, AKA "the blackhole"

I haven't checked the source for the aligned page. (Mobile browsers have the hood welded shut.) Outside <pre> I think collapsing all runs of whitespace into 1 is legit HTML presentation though. :\

## 

Jeremy W. Sherman
http://jeremywsherman.com/

**Comment by jeremy-w** [comment]
Forgot I had a Workflow to View Source. All in pre tags, lots of spans. Could be I forget the HTML weirdness; could be an Apple bug. I'll see about filing one and post the Radar ID here in case anyone wants to dupe.

**Comment by chris-martin** [comment]
I use Haddock to generate this, so seems likely that Safari has whitespace issues with all of the source code presented on Hackage as well.

**Comment by jeremy-w** [comment]
Confirmed it looks fine in desktop Safari. And all the code is in a `<pre>` tag and has style `white-space: pre`. Careful highlighting shows that Mobile Safari has the correct number of spaces; their width is off, though, which throws off alignment. Perhaps it's not using a, or the same, monospace font for the whitespace?

**Comment by jeremy-w** [comment]
Fun gap in Web Inspectors: They appear to elide whitespace text, so you can't select it to check properties.

And the moment I grab the text node and set its `nodeValue`, the whole `<pre>` containing it fixes up its presentation and aligns properly on my phone. Yeah, looks like a bug.

**Comment by jeremy-w** [comment]
Attempting to minimize. Everything works fine in a very minimal example with pre and spans. Hrm.

**Comment by jeremy-w** [comment]
Minimized. It is a very particular issue. I've filed rdar://27160931 "MobileSafari: Fails to use monospace whitespace in &lt;PRE> if all non-whitespace wrapped in &lt;SPAN>". You can demo it with this tiny example: http://codepen.io/jws/pen/OXgmOZ

As a workaround, if you change a _single_ space in each `<pre>` into a `&nbsp;`, that wakes it up to fix the issue. Yay computers.

**Comment by chris-martin** [comment]
Wow, thanks for the thorough investigation :+1:

**Comment by chris-martin** [comment]
It's now built with pandoc. Tested on my iphone se, it seems to be okay now.
